# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permutation_PREGSjoint <- function(x, Y, Z, B) {
    .Call(`_PREGS_permutation_PREGSjoint`, x, Y, Z, B)
}

PREGS_CI_table_construct <- function(Cmat) {
    .Call(`_PREGS_PREGS_CI_table_construct`, Cmat)
}

permutation_FL <- function(x, Y, Z, B) {
    .Call(`_PREGS_permutation_FL`, x, Y, Z, B)
}

permutation_vanilla <- function(x, Y, Z, B) {
    .Call(`_PREGS_permutation_vanilla`, x, Y, Z, B)
}

