# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
permutation_PREGSjoint <- function(x, Y, Z, B) {
    .Call('_PREGS_permutation_PREGSjoint', PACKAGE = 'PREGS', x, Y, Z, B)
}

#' @export
PREGS_CI_table_construct <- function(Cmat) {
    .Call('_PREGS_PREGS_CI_table_construct', PACKAGE = 'PREGS', Cmat)
}

#' @export
permutation_FL <- function(x, Y, Z, B) {
    .Call('_PREGS_permutation_FL', PACKAGE = 'PREGS', x, Y, Z, B)
}

#' @export
permutation_vanilla <- function(x, Y, Z, B) {
    .Call('_PREGS_permutation_vanilla', PACKAGE = 'PREGS', x, Y, Z, B)
}

