# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permutation_conformal_C <- function(Xresid, yfitted, yresid, U, perm_idx, type = "coef") {
    .Call('_PREGS_permutation_conformal_C', PACKAGE = 'PREGS', Xresid, yfitted, yresid, U, perm_idx, type)
}

permutation_FL_C <- function(Xresid, yfitted, yresid, U, perm_idx, type = "coef") {
    .Call('_PREGS_permutation_FL_C', PACKAGE = 'PREGS', Xresid, yfitted, yresid, U, perm_idx, type)
}

permutation_simple_C <- function(X, yresid, U, perm_idx) {
    .Call('_PREGS_permutation_simple_C', PACKAGE = 'PREGS', X, yresid, U, perm_idx)
}

